### PR TITLE
Add Yarna's Coat (Personal Item)

### PR DESCRIPTION
**Pull request by Frostbitey**
## Why / Balance
Personal Item to add more personality to specific characters!

## Media
Preview:
equipped-OUTERCLOTHING

Ingame Preview:
image
image
image
image

I do plan to update this sprite in the future, and add more details. But I'll keep it as it is for now!

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
As mentioned in the title, Added Yarna's coat! So called "Elegant Security Winter Coat"!
Also lightly changed the description of Frosty Winter Coat.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
Could you add some screenshots of the coat in game, along with the stats, please?

**Comment by Frostbitey** [comment]
> Could you add some screenshots of the coat in game, along with the stats, please?

I'll do so!- When.. I will figure out how I can actually get this visual studio SS14 server up and running...

**Comment by Tych0theSynth** [comment]
No worries! Ari pointed out that I can find the stats in the code (duh) and I can see that it's not different to regular winter coats, so that's good. 

From a GM point of view, I'm interested to know: is this a civilian clothing item for Yarna, or is this intended for use when she's working security (part of her uniform)?

**Comment by Frostbitey** [comment]
> No worries! Ari pointed out that I can find the stats in the code (duh) and I can see that it's not different to regular winter coats, so that's good.
> 
> From a GM point of view, I'm interested to know: is this a civilian clothing item for Yarna, or is this intended for use when she's working security (part of her uniform)?

There we go, THIS is the Right one!

Yes! This winter coat is for Security! Although, I've ask Yarnie them self, and they asked too if it could be used as a civilian winter coat aswell. Considering that the name is "Elegant **Security** Winter Coat", I am not sure if it will conflict with the common sense! 
But generally, Yes! It is supposed to be a part of her uniform! (Mot preferably when first time introdouced to a shift, hand it over to Frostie so that he can hand it over to Yarnie!)

**Comment by Frostbitey** [comment]
Updated!

**Review by TsjipTsjip — CHANGES_REQUESTED** [review]
The colour scheme would make this item restricted to the security department, in which case you could consider this becoming a reskin of an armoured coat instead. This cannot be merged as-is due to the colour scheme.

**Comment by Frostbitey** [comment]
> The colour scheme would make this item restricted to the security department, in which case you could consider this becoming a reskin of an armoured coat instead. This cannot be merged as-is due to the colour scheme.

Hmm..

**Comment by Frostbitey** [comment]
I'll create a new PR for this. I am not quite sure how to manage those commits in the branches. So it may be best if i just close this one.

**Pull request closed without merging**
